version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    command: ["--bind_ip_all", "--noauth"]

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/dd_db

  frontend:
    build: ./frontend
    ports:
      - "8081:8081"
    depends_on:
      - backend

volumes:
  mongo_data:
